### ISSUE TITLE
README.md文件包含坏掉的超链接

### ISSUE THREAD

**Issue by skyhgzsh** [OSCPU/yosys-sta#10]
在本项目README.md中，“* 目前支持开源PDK nangate45, 具体可阅读[nangate45的README](nangate45/README.md)”一行的超链接链接到的是空页面。
![22A8A3422616B3CA9B5198D99B510E07](https://github.com/user-attachments/assets/8652b02b-9b11-4d13-8659-38e4ced7c886)
![43511FD41E673A6DA112D4AEB5907DF7](https://github.com/user-attachments/assets/1f69b851-716c-470a-a753-9fecf1455ca2)

**Comment by sashimi-yzh** [comment]
感谢指出, 已在commit 23dd384 中修复
