### ISSUE TITLE
Crash During Static Timing Analysis of CPU Design Using ISTA

### ISSUE THREAD

**Issue by dingqingchen** [OSCPU/yosys-sta#3]
When I tried to perform static timing analysis on my CPU design using ISTA, it crashed. Here are my project files and logs.
Yosys: Yosys 0.9 (git sha1 1979e0b)
OS: Ubuntu 22.04.2 LTS (WSL2 on Win11)
CPU: 12th Gen Intel(R) Core(TM) i5-12600KF
[CrashProject](https://pan.baidu.com/s/1nqn-2ZERamAnD6uVBwfrhQ?pwd=7oo2)

**Comment by simintao** [comment]
新版本d9c76846ce6e28304fe193503daa05d7efa8c4cc已经解决，待新版本发布

**Comment by sashimi-yzh** [comment]
已修复, 并修改为通过`wget`拉取最新版本的iSTA, 请移除并重新克隆本项目, 尝试能否通过测试.
